services:
  java:
    image: amazoncorretto:21
    container_name: java21_back
    working_dir: /app/src
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    tty: true
    # command: sh -c "yarn install && yarn dev"
  db:
    image: postgres:17
    container_name: postgres17_back
    environment: 
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'
    # volumes:
    #   - ./data:/var/lib/postgresql/data